# Makefile example

install:
	bundle check || bundle install

db-migrate: migrate

etl-migrate: migrate

migrate:
	@echo "This application does not have migrations"
	@exit 0

.PHONY: db-migrate etl-migrate
